package mypack;
// Generated 20 Jan, 2020 5:18:27 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name = "cart", catalog = "emart")
public class Cart implements java.io.Serializable {

	private Integer oid;
	private Product product;
	private int quantity;
	private boolean pointchkbox;
	private String address;
	//private Set<Invoice> invoices = new HashSet<Invoice>(0);

	public Cart() {
	}

	public Cart(Product product, int quantity, boolean pointchkbox, String address) {
		this.product = product;
		this.quantity = quantity;
		this.pointchkbox = pointchkbox;
		this.address = address;
	}

	/*public Cart(Product product, int quantity, boolean pointchkbox, String address, Set<Invoice> invoices) {
		this.product = product;
		this.quantity = quantity;
		this.pointchkbox = pointchkbox;
		this.address = address;
		//this.invoices = invoices;
	}*/

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "oid", unique = true, nullable = false)
	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	@ManyToOne
	@JoinColumn(name = "pid", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "pointchkbox", nullable = false)
	public boolean isPointchkbox() {
		return this.pointchkbox;
	}

	public void setPointchkbox(boolean pointchkbox) {
		this.pointchkbox = pointchkbox;
	}

	@Column(name = "address", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	/*@JsonIgnore
	@OneToMany(cascade = CascadeType.ALL, mappedBy = "cart")
	public Set<Invoice> getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Set<Invoice> invoices) {
		this.invoices = invoices;
	}*/

}
