package mypack;
// Generated 20 Jan, 2020 5:18:27 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Catsubcat generated by hbm2java
 */
@Entity
@Table(name = "catsubcat", catalog = "emart")
public class Catsubcat implements java.io.Serializable {

	private Integer cid;
	private String name;
	private String cname;
	private boolean flag;
	private Set<Product> products = new HashSet<Product>(0);

	public Catsubcat() {
	}

	public Catsubcat(String name, boolean flag) {
		this.name = name;
		this.flag = flag;
	}

	public Catsubcat(String name, String cname, boolean flag , Set<Product> products) {
		this.name = name;
		this.cname = cname;
		this.flag = flag;
		this.products = products;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cid", unique = true, nullable = false)
	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "cname", length = 20)
	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	@Column(name = "flag", nullable = false)
	public boolean isFlag() {
		return this.flag;
	}

	public void setFlag(boolean flag) {
		this.flag = flag;
	}

	@JsonIgnore
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "catsubcat")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
