package mypack;
// Generated 20 Jan, 2020 5:18:27 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "emart", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
public class Customer implements java.io.Serializable {

	private Integer custid;
	private String name;
	private String email;
	private String mobno;
	private int age;
	private String gender;
	private String password;
	private String address;
	private boolean primemember;
	private int points;
//	private Set<Invoice> invoices = new HashSet<Invoice>(0);

	public Customer() {
	}

	public Customer(String name, String email, String mobno, int age, String gender, String password, String address,
			boolean primemember, int points) {
		this.name = name;
		this.email = email;
		this.mobno = mobno;
		this.age = age;
		this.gender = gender;
		this.password = password;
		this.address = address;
		this.primemember = primemember;
		this.points = points;
	}

	/*public Customer(String name, String email, String mobno, int age, String gender, String password, String address,
			boolean primemember, int points, Set<Invoice> invoices) {
		this.name = name;
		this.email = email;
		this.mobno = mobno;
		this.age = age;
		this.gender = gender;
		this.password = password;
		this.address = address;
		this.primemember = primemember;
		this.points = points;
		this.invoices = invoices;
	}*/

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "custid", unique = true, nullable = false)
	public Integer getCustid() {
		return this.custid;
	}

	public void setCustid(Integer custid) {
		this.custid = custid;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", unique = true, nullable = false, length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "mobno", nullable = false, length = 13)
	public String getMobno() {
		return this.mobno;
	}

	public void setMobno(String mobno) {
		this.mobno = mobno;
	}

	@Column(name = "age", nullable = false)
	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	@Column(name = "gender", nullable = false, length = 10)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "password", nullable = false, length = 15)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "address", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "primemember", nullable = false)
	public boolean isPrimemember() {
		return this.primemember;
	}

	public void setPrimemember(boolean primemember) {
		this.primemember = primemember;
	}

	@Column(name = "points", nullable = false)
	public int getPoints() {
		return this.points;
	}

	public void setPoints(int points) {
		this.points = points;
	}

	/*@JsonIgnore
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Invoice> getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Set<Invoice> invoices) {
		this.invoices = invoices;*
	}*/

}
