package mypack;
// Generated 20 Jan, 2020 5:18:27 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "emart")
public class Product implements java.io.Serializable {

	private Integer pid;
	private Catsubcat catsubcat;
	private String pname;
	private String pdet;
	private int redeempoints;
	private double price;
	private double primeprice;
	private String image;
	private String modelno;
	private double cgst;
	private double sgst;
	//private Set<Cart> carts = new HashSet<Cart>(0);

	public Product() {
	}

	public Product(Catsubcat catsubcat, String pname, String pdet, int redeempoints, double price, double primeprice,
			String image, String modelno, double cgst, double sgst) {
		this.catsubcat = catsubcat;
		this.pname = pname;
		this.pdet = pdet;
		this.redeempoints = redeempoints;
		this.price = price;
		this.primeprice = primeprice;
		this.image = image;
		this.modelno = modelno;
		this.cgst = cgst;
		this.sgst = sgst;
	}
/*
	public Product(Catsubcat catsubcat, String pname, String pdet, int points, double price, double primeprice,
			String image, String modelno, double cgst, double sgst, Set<Cart> carts) {
		this.catsubcat = catsubcat;
		this.pname = pname;
		this.pdet = pdet;
		this.points = points;
		this.price = price;
		this.primeprice = primeprice;
		this.image = image;
		this.modelno = modelno;
		this.cgst = cgst;
		this.sgst = sgst;
		this.carts = carts;
	}
*/
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pid", unique = true, nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@ManyToOne
	@JoinColumn(name = "cid", nullable = false)
	public Catsubcat getCatsubcat() {
		return this.catsubcat;
	}

	public void setCatsubcat(Catsubcat catsubcat) {
		this.catsubcat = catsubcat;
	}

	@Column(name = "pname", nullable = false, length = 20)
	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	@Column(name = "pdet", nullable = false)
	public String getPdet() {
		return this.pdet;
	}

	public void setPdet(String pdet) {
		this.pdet = pdet;
	}

	@Column(name = "redeempoints", nullable = false)
	public int getRedeempoints() {
		return this.redeempoints;
	}

	public void setRedeempoints(int redeempoints) {
		this.redeempoints = redeempoints;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "primeprice", nullable = false, precision = 22, scale = 0)
	public double getPrimeprice() {
		return this.primeprice;
	}

	public void setPrimeprice(double primeprice) {
		this.primeprice = primeprice;
	}

	@Column(name = "image", nullable = false, length = 60)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "modelno", nullable = false, length = 30)
	public String getModelno() {
		return this.modelno;
	}

	public void setModelno(String modelno) {
		this.modelno = modelno;
	}

	@Column(name = "cgst", nullable = false, precision = 22, scale = 0)
	public double getCgst() {
		return this.cgst;
	}

	public void setCgst(double cgst) {
		this.cgst = cgst;
	}

	@Column(name = "sgst", nullable = false, precision = 22, scale = 0)
	public double getSgst() {
		return this.sgst;
	}

	public void setSgst(double sgst) {
		this.sgst = sgst;
	}

	/*@JsonIgnore
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Cart> getCarts() {
		return this.carts;
	}

	public void setCarts(Set<Cart> carts) {
		this.carts = carts;
	}*/

}
